[package]
name = "brainfuck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalrpop-util = "0.20.2"
logos = "0.14.0"

[build-dependencies]
lalrpop = "0.20.2"